#! python3.11
"""
--- Day 9: Rope Bridge ---
This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.

You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where not to step.

Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.

Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical series of motions (your puzzle input) for the head, you can determine how the tail will move.

Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):

....
.TH.
....

....
.H..
..T.
....

...
.H. (H covers T)
...

If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:

.....    .....    .....
.TH.. -> .T.H. -> ..TH.
.....    .....    .....

...    ...    ...
.T.    .T.    ...
.H. -> ... -> .T.
...    .H.    .H.
...    ...    ...

Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:

.....    .....    .....
.....    ..H..    ..H..
..H.. -> ..... -> ..T..
.T...    .T...    .....
.....    .....    .....

.....    .....    .....
.....    .....    .....
..H.. -> ...H. -> ..TH.
.T...    .T...    .....
.....    .....    .....

You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.

For example:

R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2

This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):

== Initial State ==

......
......
......
......
H.....  (H covers T, s)

== R 4 ==

......
......
......
......
TH....  (T covers s)

......
......
......
......
sTH...

......
......
......
......
s.TH..

......
......
......
......
s..TH.

== U 4 ==

......
......
......
....H.
s..T..

......
......
....H.
....T.
s.....

......
....H.
....T.
......
s.....

....H.
....T.
......
......
s.....

== L 3 ==

...H..
....T.
......
......
s.....

..HT..
......
......
......
s.....

.HT...
......
......
......
s.....

== D 1 ==

..T...
.H....
......
......
s.....

== R 4 ==

..T...
..H...
......
......
s.....

..T...
...H..
......
......
s.....

......
...TH.
......
......
s.....

......
....TH
......
......
s.....

== D 1 ==

......
....T.
.....H
......
s.....

== L 5 ==

......
....T.
....H.
......
s.....

......
....T.
...H..
......
s.....

......
......
..HT..
......
s.....

......
......
.HT...
......
s.....

......
......
HT....
......
s.....

== R 2 ==

......
......
.H....  (H covers T)
......
s.....

......
......
.TH...
......
s.....
After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

..##..
...##.
.####.
....#.
s###..
So, there are 13 positions the tail visited at least once.

Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?


Your puzzle answer was 5981.

The first half of this puzzle is complete! It provides one gold star: *


--- Part Two ---
A rope snaps! Suddenly, the river is getting a lot closer than you remember. The bridge is still there, but some of the ropes that broke are now whipping toward you as you fall through the air!

The ropes are moving too quickly to grab; you only have a few seconds to choose how to arch your body to avoid being hit. Fortunately, your simulation can be extended to support longer ropes.

Rather than two knots, you now must simulate a rope consisting of ten knots. One knot is still the head of the rope and moves according to the series of motions. Each knot further down the rope follows the knot in front of it using the same rules as before.

Using the same series of motions as the above example, but with the knots marked H, 1, 2, ..., 9, the motions now occur as follows:

== Initial State ==

......
......
......
......
H.....  (H covers 1, 2, 3, 4, 5, 6, 7, 8, 9, s)

== R 4 ==

......
......
......
......
1H....  (1 covers 2, 3, 4, 5, 6, 7, 8, 9, s)

......
......
......
......
21H...  (2 covers 3, 4, 5, 6, 7, 8, 9, s)

......
......
......
......
321H..  (3 covers 4, 5, 6, 7, 8, 9, s)

......
......
......
......
4321H.  (4 covers 5, 6, 7, 8, 9, s)

== U 4 ==

......
......
......
....H.
4321..  (4 covers 5, 6, 7, 8, 9, s)

......
......
....H.
.4321.
5.....  (5 covers 6, 7, 8, 9, s)

......
....H.
....1.
.432..
5.....  (5 covers 6, 7, 8, 9, s)

....H.
....1.
..432.
.5....
6.....  (6 covers 7, 8, 9, s)

== L 3 ==

...H..
....1.
..432.
.5....
6.....  (6 covers 7, 8, 9, s)

..H1..
...2..
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

.H1...
...2..
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

== D 1 ==

..1...
.H.2..
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

== R 4 ==

..1...
..H2..
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

..1...
...H..  (H covers 2)
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

......
...1H.  (1 covers 2)
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

......
...21H
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

== D 1 ==

......
...21.
..43.H
.5....
6.....  (6 covers 7, 8, 9, s)

== L 5 ==

......
...21.
..43H.
.5....
6.....  (6 covers 7, 8, 9, s)

......
...21.
..4H..  (H covers 3)
.5....
6.....  (6 covers 7, 8, 9, s)

......
...2..
..H1..  (H covers 4; 1 covers 3)
.5....
6.....  (6 covers 7, 8, 9, s)

......
...2..
.H13..  (1 covers 4)
.5....
6.....  (6 covers 7, 8, 9, s)

......
......
H123..  (2 covers 4)
.5....
6.....  (6 covers 7, 8, 9, s)

== R 2 ==

......
......
.H23..  (H covers 1; 2 covers 4)
.5....
6.....  (6 covers 7, 8, 9, s)

......
......
.1H3..  (H covers 2, 4)
.5....
6.....  (6 covers 7, 8, 9, s)
Now, you need to keep track of the positions the new tail, 9, visits. In this example, the tail never moves, and so it only visits 1 position. However, be careful: more types of motion are possible than before, so you might want to visually compare your simulated rope to the one above.

Here's a larger example:

R 5
U 8
L 8
D 3
R 17
D 10
L 25
U 20
These motions occur as follows (individual steps are not shown):

== Initial State ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
...........H..............  (H covers 1, 2, 3, 4, 5, 6, 7, 8, 9, s)
..........................
..........................
..........................
..........................
..........................

== R 5 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
...........54321H.........  (5 covers 6, 7, 8, 9, s)
..........................
..........................
..........................
..........................
..........................

== U 8 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
................H.........
................1.........
................2.........
................3.........
...............54.........
..............6...........
.............7............
............8.............
...........9..............  (9 covers s)
..........................
..........................
..........................
..........................
..........................

== L 8 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
........H1234.............
............5.............
............6.............
............7.............
............8.............
............9.............
..........................
..........................
...........s..............
..........................
..........................
..........................
..........................
..........................

== D 3 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
.........2345.............
........1...6.............
........H...7.............
............8.............
............9.............
..........................
..........................
...........s..............
..........................
..........................
..........................
..........................
..........................

== R 17 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
................987654321H
..........................
..........................
..........................
..........................
...........s..............
..........................
..........................
..........................
..........................
..........................

== D 10 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
...........s.........98765
.........................4
.........................3
.........................2
.........................1
.........................H

== L 25 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
...........s..............
..........................
..........................
..........................
..........................
H123456789................

== U 20 ==

H.........................
1.........................
2.........................
3.........................
4.........................
5.........................
6.........................
7.........................
8.........................
9.........................
..........................
..........................
..........................
..........................
..........................
...........s..............
..........................
..........................
..........................
..........................
..........................

Now, the tail (9) visits 36 positions (including s) at least once:

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
#.........................
#.............###.........
#............#...#........
.#..........#.....#.......
..#..........#.....#......
...#........#.......#.....
....#......s.........#....
.....#..............#.....
......#............#......
.......#..........#.......
........#........#........
.........########.........
Simulate your complete series of motions on a larger rope with ten knots. How many positions does the tail of the rope visit at least once?


Your puzzle answer was 2352.

Both parts of this puzzle are complete! They provide two gold stars: **

"""
import math

test_data = ['R4',
			 'U4',
			 'L3',
			 'D1',
			 'R4',
			 'D1',
			 'L5',
			 'R2'
			]

test_data_1 = [ ['R', 4],
				['U', 4],
				['L', 3],
				['D', 1],
				['R', 4],
				['D', 1],
				['L', 5],
				['R', 2]
			]

test_data_2 = [ ['R', 5],
				['U', 8],
				['L', 8],
				['D', 3],
				['R', 17],
				['D', 10],
				['L', 25],
				['U', 20]
			]

MOVE_LEFT 	= 'L'
MOVE_RIGHT 	= 'R'
MOVE_UP 	= 'U'
MOVE_DOWN 	= 'D'


class Rope():

	def __init__(self, name, parent = None, child = None, x = 0, y = 0):
		self._moves = [[0,0]]
		self.name = name

		self.parent = parent
		self.child = child

		self.x = x
		self.y = y

	def __repr__(self):
		return f"<{self.__class__.__name__} object '{self.name}'> at [{self.x},{self.y}]"

	def get_position( self ):
		return [self.x, self.y]


	def move(self, vector):
		direction, magnitude = vector

		if direction == MOVE_LEFT:
			self.x -= magnitude

		elif direction == MOVE_RIGHT:
			self.x += magnitude

		elif direction == MOVE_UP:
			self.y += magnitude

		elif direction == MOVE_DOWN:
			self.y -= magnitude

		else:
			pass

		if self.child:
			self.move_child(vector)

		self._moves.append(self.get_position())

	def move_child(self, vector, child_move = False):
		direction, magnitude = vector

		delta_x = self.x - self.child.x
		delta_y = self.y - self.child.y

		# Head and tail are touching
		if [abs(delta_x), abs(delta_y)] in [[0,0], [0,1], [1,1], [1,0]]:
			pass # Do nothing.

		# Head two steps directly up, down, left or right
		elif [abs(delta_x), abs(delta_y)] in [[0,2], [2,0]]:
			# Take a step to stay close
			if abs(delta_x) == 2:
				self.child.x = self.child.x + int(delta_x/2)

			else: # abs(delta_y) == 2
				self.child.y = self.child.y + int(delta_y/2)

		# Head and tail AREN'T touching and aren't in the same row or column
		else:
			if abs(delta_x) == 2 and abs(delta_y) == 2:
				self.child.x = math.ceil((self.x + self.child.x)/2)
				self.child.y = math.ceil((self.y + self.child.y)/2)
			else:
				if self.x != self.child.x  and self.y != self.child.y:
					if abs(delta_x) > 1:
						if direction == MOVE_LEFT:
							self.child.x = math.ceil((self.x + self.child.x)/2)
						else:
							self.child.x = math.ceil((self.x + self.child.x)/2)
						self.child.y = self.child.y + delta_y

					elif abs(delta_y) > 1:
						self.child.x = self.child.x + delta_x
						if direction == MOVE_DOWN:
							self.child.y = math.ceil((self.y + self.child.y)/2)
						else:
							self.child.y = math.ceil((self.y + self.child.y)/2)

		self.child._moves.append(self.child.get_position())

		# Move child segments
		if self.child and self.child.child:
			next_dir = ''
			if delta_x > 0:
				next_dir = 'R'
				next_mag = delta_x
			elif delta_x < 0:
				next_dir = 'L'
				next_mag = delta_x
			elif delta_y > 0:
				next_dir = 'U'
				next_mag = delta_y
			else:
				next_dir = 'D'
				next_mag = delta_y

			self.child.move_child([next_dir, next_mag], child_move = True)


def parse_data(raw_data):
	data = [[x[0], int(x[1:])] for x in raw_data]
	return data


def _get_screen_coord(move, grid_dimension):
	x = move[0] + int(grid_dimension/2)
	y = move[1] + int(grid_dimension/2)

	return x, y


def draw(rope_obj, height = 25, width = 25, all_steps = False):
	render_grid = []
	data = rope_obj[0]._moves

	if not all_steps:
		render_grid = _make_grid(height, width)

	# Populate the grid
	for move_num,i in enumerate(data):
		if all_steps: render_grid = _make_grid(height, width)
		for obj in rope_obj:
			obj_x = obj._moves[move_num][0] + width
			obj_y = obj._moves[move_num][1] + height
			render_grid[obj_y][obj_x] = obj.name

		if all_steps:
			temp_grid = render_grid.copy()
			temp_grid.reverse()
			for row in temp_grid:
				output = ''.join([x if type(x) != int else '.' for x in row])
				print(output)
			print()

	if not all_steps:
		temp_grid = render_grid.copy()
		temp_grid.reverse()
		for row in temp_grid:
			output = ''.join([x if type(x) != int else '.' for x in row])
			print(output)
		print()


def _make_grid(width, height):
	grid = []
	grid_dimension = max(width, height)
	row = ['.'] * (grid_dimension * 2 + 1)

	grid.append(row.copy())
	for i in range(0, grid_dimension * 2):
		grid.append(row.copy())

	# Draw the start
	grid[height][width] = 's'

	return grid


def part_one(data, height = 5, width = 5, render = True):
	rope_head = Rope('H')
	rope_tail = Rope('T',parent = rope_head)
	rope_head.child = rope_tail

	for vector in data:
		direction, magnitude = vector
		for i in range(magnitude):
			rope_head.move((direction, 1))
			# print(f'[{vector[0]} {vector[1]}]:\t{rope_head.get_position()}')
			# print(f'\t\t{rope_tail.get_position()}\n')
		# print(f'[{vector[0]} {vector[1]}]:\t{rope_head.get_position()}')
		# print(f'\t\t{rope_tail.get_position()}\n')

	if render:
		# draw([rope_tail, rope_head], 5, 5, all_steps = True)
		rope_tail.name = '#'
		draw([rope_tail], height, width)

	unique_positions = len([list(x) for x in set(tuple(x) for x in rope_tail._moves)])
	print(f'Tail has visited {unique_positions} positions at least once')


def part_two(data, height = 10, width = 10, render = True):
	rope_head = Rope('H')
	rope_knot1 = Rope('1', parent = rope_head)
	rope_knot2 = Rope('2', parent = rope_knot1)
	rope_knot3 = Rope('3', parent = rope_knot2)
	rope_knot4 = Rope('4', parent = rope_knot3)
	rope_knot5 = Rope('5', parent = rope_knot4)
	rope_knot6 = Rope('6', parent = rope_knot5)
	rope_knot7 = Rope('7', parent = rope_knot6)
	rope_knot8 = Rope('8', parent = rope_knot7)
	rope_knot9 = Rope('9',parent = rope_knot8)

	rope_head.child = rope_knot1
	rope_knot1.child = rope_knot2
	rope_knot2.child = rope_knot3
	rope_knot3.child = rope_knot4
	rope_knot4.child = rope_knot5
	rope_knot5.child = rope_knot6
	rope_knot6.child = rope_knot7
	rope_knot7.child = rope_knot8
	rope_knot8.child = rope_knot9

	rope = [rope_head, rope_knot1, rope_knot2, rope_knot3, rope_knot4, rope_knot5, rope_knot6, rope_knot7, rope_knot8, rope_knot9]

	for vector in data:
		direction, magnitude = vector
		for i in range(magnitude):
			rope_head.move((direction, 1))
			# print(f'[{vector[0]} {vector[1]}]:\t{rope_head.get_position()} - H')
			# print(f'\t\t{rope_knot1.get_position()} - {rope_knot1.name}')
			# print(f'\t\t{rope_knot2.get_position()} - {rope_knot2.name}')
			# print(f'\t\t{rope_knot3.get_position()} - {rope_knot3.name}')
			# print(f'\t\t{rope_knot4.get_position()} - {rope_knot4.name}')
			# print(f'\t\t{rope_knot5.get_position()} - {rope_knot5.name}')
			# print(f'\t\t{rope_knot6.get_position()} - {rope_knot6.name}')
			# print(f'\t\t{rope_knot7.get_position()} - {rope_knot7.name}')
			# print(f'\t\t{rope_knot8.get_position()} - {rope_knot8.name}')
			# print(f'\t\t{rope_knot9.get_position()} - T')
			# print()

	if render:
		rope.reverse()
		draw(rope, height, width, all_steps = True)

	unique_positions = len([list(x) for x in set(tuple(x) for x in rope_knot9._moves)])
	print(f'Tail has visited {unique_positions} positions at least once')


def main(raw_data):
	data = parse_data(raw_data)

	part_one(data, render = False)
	part_two(data, render = False)



if __name__ == "__main__":
	input = r"D:\Projects\Advent_of_Code\2022\day_09_input.txt"
	raw_data = []

	with open(input, "r") as input_file:
		raw_data = [line.replace(' ','').strip() for line in input_file.readlines()]

	# part_one(parse_data(test_data))
	# part_two(test_data_1)
	# part_two(test_data_2, height = 15, width = 15)
	main(raw_data)